.\" Process this file with
.\" groff -man -Tascii foo.1
.\" 
.TH "" "1" "August 2013" "Ulrich Schmidt" "User Manuals"
.SH "UliEdit Pro"
UliEdit Pro ist ein grafischer Text\-Editor fuer Programmierer.
.SH "SYNOPSIS"
.B ulieditpro \-r [filename]
.SH "DESCRIPTION"
UliEdit ist ein grafischer Texteditor fuer Programmierer der unter anderem Zeilennummern, Automatische Einrueckung und vieles mehr bietet.
.SH "OPTIONS"
.IP \-r
Datei schreibgeschuetzt oeffnen
.SH "ENVIRONMENT"
.IP PRINT_CMD
Der Standardbefehl fuer den Ausdruck einer Datei

\fBBeispiel\-Wert:\fR
lpr \-o portrait \-J "$title" %1

.IP FONT_SIZE
Die Schriftgroesse im Editor in pt

.SH "AUTHOR"
Ulrich Schmidt
